#!/usr/bin/ruby
#
# Copyright Mark Longair (c) 2002, 2005, 2008 Reuben Thomas (c) 2005-2007.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>. 
# 
# This is a simple script for fetching mail from POP3 accounts.
# On a Debian system, you'll need the following packages:
#
#   ruby
#   libruby
#   libopenssl-ruby
#   libsqlite3-ruby
#
# See http://mythic-beasts.com/~mark/software/stand/
# for further remarks.

$program_name = 'stand'

require 'getoptlong'
require 'yaml'
require 'socket'
require 'net/pop'
require 'openssl'
require 'timeout'
require 'sqlite3'

# FIXME: I don't understand the recent changes that have been made to
# InternetMessageIO and broke the old version of these two classes, so
# while this seems to work at the moment, I expect it to break at any
# time.

module Net

  class SSLIO < InternetMessageIO

    def SSLIO.old_open(addr, port, open_timeout = 30, read_timeout = 30, debug_output = nil)

      tcp_socket = timeout(open_timeout) { TCPsocket.new(addr, port) }

      @ssl_context = OpenSSL::SSL::SSLContext.new()

      if $ssl_verify
        @ssl_context.ca_path = '/etc/ssl/certs'
        @ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER
      else
        @ssl_context.verify_mode = OpenSSL::SSL::VERIFY_NONE
      end

      socket = OpenSSL::SSL::SSLSocket.new(tcp_socket, @ssl_context)

      socket.connect

      io = new(socket)
      io.read_timeout = read_timeout
      io.debug_output = debug_output
      io

    end

  end

end

# ----------------------------------------------------------------------
#
# POP3 over SSL class

module Net

  class POP3s < POP3

    def self.port
      '995'
    end

    def POP3s.socket_type
      SSLIO
    end

  end

end

# ----------------------------------------------------------------------
#
# Command line argument parsing...

# Some default values...

$configuration_file = "#{ENV['HOME']}/.stand.yaml"
$configuration_file_pretty = "~/.stand.yaml"
$uidl_database_filename = "#{ENV['HOME']}/.stand-uidls"

def usage

  print <<EOF
Usage: #{$program_name} [OPTION]...

  -h, --help           Display this message and exit.
  -d, --delete         Delete messages on server after fetching.
  -n, --no-ssl-verify  Don\'t verify the peer\'s certificate when using SSL.
  -f <FILENAME>, --configuration-file=<FILENAME>
                       Specify the configuration file to use.
                       (default: #{$configuration_file_pretty})
  -r <SECONDS>, --reconnect-after=<SECONDS>
                       Reconnect to the server if <SECONDS> seconds has
                       elapsed since the last connection.
EOF

end

options = GetoptLong.new(
  [ "--help", "-h", GetoptLong::NO_ARGUMENT ],
  [ "--delete", "-d", GetoptLong::NO_ARGUMENT ],
  [ "--no-ssl-verify", "-n", GetoptLong::NO_ARGUMENT ],
  [ "--configuration-file", "-f", GetoptLong::REQUIRED_ARGUMENT ],
  [ "--reconnect-after", "-r",  GetoptLong::REQUIRED_ARGUMENT ]
)

$keep = true
$ssl_verify = true
$reconnect_after = nil

begin

  options.each do |opt, arg|

    case opt
    when "--help"
      usage
      exit
    when "--delete"
      $keep = false
    when "--no-ssl-verify"
      $ssl_verify = false
    when "--configuration-file"
      $configuration_file = arg
    when "--reconnect-after"
      $reconnect_after = Float(arg)
    end

  end

rescue

  print "Bad command line option: " + $! + "\n"
  usage
  exit

end

if $keep and $reconnect_after
  puts "There should be no reason to specify --reconnect-after with --keep"
  exit
end

# ----------------------------------------------------------------------

# A fairly idiotic progress class.

class Progress

  def initialize(maximum)
    @maximum = maximum
    @current_value = 0
  end

  def increase_by(i)
    set @current_value + i
  end

  def set(v)
    block_change = (v / 1024) - (@current_value / 1024)
    if block_change >= 0
      (1..block_change).each { print "." }
      $stdout.flush
    else
      backspaces = - block_change
      (1..backspaces).each { print "\b" }
      $stdout.flush
    end
    @current_value = v
  end

end

# ----------------------------------------------------------------------

# This class deals with connecting to a POP3 server, and fetching the
# mail from it.

class POP3Account

  attr_accessor :host, :user, :port

  attr_reader :command

  def initialize(host, user, password, use_ssl, use_apop, port, command)
    @host = host
    @user = user
    @password = password
    @use_ssl = use_ssl
    @use_apop = use_apop
    @port = port
    @command = command
  end

  def to_s
    "#{@user} at #{@host}:#{@port}#{ @use_ssl ? ' (SSL)' : ''}"
  end
  
  def account_uidl(uidl)
    "#{@user}@#{@host}:#{@port}##{uidl}"
  end

  # These three methods manipulate the UIDL database.

  def add_uidl_to_db(db,u)
    db.execute( "INSERT INTO uidls VALUES (?)", account_uidl(u) )
  end

  def delete_uidls_from_db(db,a)
    a.each do |u|
      db.execute( "DELETE FROM uidls WHERE uidl = ?", account_uidl(u) )
    end
  end

  def db_has_uidl?(db,u)
    rows = db.execute( "SELECT uidl FROM uidls WHERE uidl = ?", account_uidl(u) )
    rows.length > 0
  end

  # Fetch all the new messages from this POP3 account, deleting
  # successfully downloaded messages.

  def fetch_all

    # Choose correct POP class

    if @use_ssl
      pop3_class = Net::POP3s
    else
      pop3_class = Net::POP3
    end

    # Process all the messages

    i = 0
    total = 0

    while true

      delete_list = []

      pop3_class.start(@host, @port, @user, @password, @use_apop) do |pop|
          
        connected_at = Time.now
        
        if i == 0 and not pop.mails.empty?
          total = pop.n_mails
          plural = total != 1
          puts "  There " + (plural ? "are" : "is") + " #{total} message" +
            (plural ? "s" : "") + " available."
        end
        
        if i >= total
          if i == 0
            puts "  No mail."
          end
          return
        end
        
        pop.each_mail do |m|
          
          i += 1
          
          print "  Retrieving message #{i} of #{total} [#{m.length} bytes]: "
          
          uidl = m.uidl
          $db.transaction
          if db_has_uidl? $db, uidl
            if $keep
              puts " [Skipping]"
            else
              puts " [Skipping, Deleting]"
              m.delete
              delete_list.push uidl
            end
            $db.commit
            next
          end
          
          progress = Progress.new(m.size)
          
          # Fetch the message...
          message = ""
          m.pop do |chunk|
            chunk.gsub!(/\r\n/, "\n")
            message << chunk
            progress.increase_by chunk.length
          end
          
          # Deliver the message...
          Kernel.open("|-", "w+") do |f|
            if f
              f.write message
            else
              begin
                exec @command
              rescue
                raise "Couldn't exec \"#{@command}\": #{$!}\n"
              end
            end
          end
          
          if $?.success?
            unless add_uidl_to_db $db, uidl
              $db.rollback
              raise "Adding the UIDL to the database failed."
            end
          else
            $db.rollback
            raise "The command \"#{@command}\" failed with exit code #{$?.exitstatus}"
          end
          $db.commit
          
          # We've successfully dealt with the message now...
          if $keep
            print " [Fetched]"
          else
            print " [Fetched, Deleting]"
            m.delete
            delete_list.push uidl
          end
          puts
          
          if $reconnect_after and Time.now - connected_at >= $reconnect_after
            break
          end
          
        end
      end

      $db.transaction do |db|
        delete_uidls_from_db db, delete_list
      end
      
    end
  end

end

# ----------------------------------------------------------------------

begin

  # Make sure that the UIDL database file is present.

  $db = SQLite3::Database.new($uidl_database_filename)

  $db.execute( "CREATE TABLE IF NOT EXISTS uidls ( uidl TEXT PRIMARY KEY )" )

  # Read in the configuration file...

  accounts = open($configuration_file, "r") { |f| YAML.load(f) }
  raise "No accounts specified in configuration file." if accounts.length == 0

  # This is the main loop.  Go through every account, fetching all the
  # new mail...

  accounts.each_index do |i|

    a = accounts[i]

    # Do some quick checks on what we've just parsed...

    valid_account_properties = ['Host', 'User', 'Pass', 'Command', 'SSL', 'APOP', 'Port']

    (a.keys - valid_account_properties).each do |property|
      puts "Warning: in account #{i + 1}, the unknown account property `#{property}' was ignored."
    end

    ['Host', 'User', 'Pass'].each do |required|
      raise "Missing `#{required}:' line in account #{i + 1}" unless a[required]
      unless a[required].class == String
        raise "The value in the `#{required}:' property of account #{i + 1} " +
          "(`#{a[required].to_s}' was not interpreted as a string; you " +
          "may need to quote it"
      end
    end

    ['SSL', 'APOP'].each do |boolean|
      if a['boolean']
        unless [ TrueClass, FalseClass ].include? a[boolean].class
          raise "In account #{i + 1}, `#{boolean}' property must be `yes', `no', `true' or `false'"
        end
      end
    end

    if a['Port']
      unless a['Port'].class == Fixnum
        raise "In account #{i + 1} the Port property must be an integer (not `#{a['Port']}\')"
      end
    else
      a['Port'] = a['SSL'] ? 995 : 110
    end

    unless a['Command']
      a['Command'] = 'procmail -f-'
    end

    account = POP3Account.new(a['Host'], a['User'], a['Pass'], a['SSL'],
                              a['APOP'], a['Port'], a['Command'])

    begin
      puts "Checking account: #{account}"
      puts "  Piping mail to the command: #{account.command}"
      account.fetch_all
    rescue Interrupt => e
      $db.rollback if $db.transaction_active?
      puts "Interrupt received: exiting."
      puts "  The exception was: #{$!}, with backtrace:"
      puts "    " + e.backtrace.join("\n    ")
      break
    rescue
      $db.rollback if $db.transaction_active?
      puts "  Error fetching mail from account `#{account}': " + $!
    end

  end

rescue
  puts "Fatal error: " + $!
end
