Document: stand
Title: Debian stand Manual
Author: <insert document author here>
Abstract: This manual describes what stand is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/stand/stand.sgml.gz

Format: postscript
Files: /usr/share/doc/stand/stand.ps.gz

Format: text
Files: /usr/share/doc/stand/stand.text.gz

Format: HTML
Index: /usr/share/doc/stand/html/index.html
Files: /usr/share/doc/stand/html/*.html

  
